"""remove  approver_id from request_tracking

Revision ID: 1b0128b7314b
Revises: abaf58f17995
Create Date: 2026-02-24 19:06:16.470383

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b0128b7314b"
down_revision: Union[str, Sequence[str], None] = "abaf58f17995"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("request_tracking_approver_id_fkey"),
        "request_tracking",
        type_="foreignkey",
    )
    op.drop_column("request_tracking", "approver_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "request_tracking",
        sa.Column("approver_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("request_tracking_approver_id_fkey"),
        "request_tracking",
        "users",
        ["approver_id"],
        ["id"],
    )
    # ### end Alembic commands ###
