"""rename request.status to current_status

Revision ID: 626fe01567d4
Revises: 934c532e6835
Create Date: 2026-02-16 22:00:27.939361

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "626fe01567d4"
down_revision: Union[str, Sequence[str], None] = "934c532e6835"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("requests", "status", new_column_name="current_status")
    op.create_index(
        "ix_requests_dashboard",
        "requests",
        ["requester_id", "current_status", "updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_requests_dashboard", table_name="requests")
    op.alter_column("requests", "current_status", new_column_name="status")
    # ### end Alembic commands ###
