"""rename request.status to current_status

Revision ID: 626fe01567d4
Revises: 934c532e6835
Create Date: 2026-02-16 22:00:27.939361

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "626fe01567d4"
down_revision: Union[str, Sequence[str], None] = "934c532e6835"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("requests", "status", new_column_name="current_status")
    op.create_index(
        "ix_requests_dashboard",
        "requests",
        ["requester_id", "current_status", "updated_at"],
        unique=False,
    )
    # op.add_column('requests', sa.Column('current_status', sa.Enum('DRAFT', 'SUBMITTED', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='status'), nullable=False))
    # op.create_index('ix_requests_dashboard', 'requests', ['requester_id', 'current_status', 'created_at'], unique=False)
    # op.drop_column('requests', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_requests_dashboard", table_name="requests")
    op.alter_column("requests", "current_status", new_column_name="status")
    # op.add_column('requests', sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', name='status'), autoincrement=False, nullable=False))
    # op.drop_index('ix_requests_dashboard', table_name='requests')
    # op.drop_column('requests', 'current_status')
    # ### end Alembic commands ###
