"""add cascade delete to request_tracking

Revision ID: 76e3f7a32886
Revises: 43a8255a3fc2
Create Date: 2026-03-25 13:41:01.272908

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76e3f7a32886"
down_revision: Union[str, Sequence[str], None] = "43a8255a3fc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("request_tracking_request_id_fkey"), "request_tracking", type_="foreignkey"
    )
    op.create_foreign_key(
        "request_tracking_request_id_fkey",
        "request_tracking",
        "requests",
        ["request_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "request_tracking_request_id_fkey", "request_tracking", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("request_tracking_request_id_fkey"),
        "request_tracking",
        "requests",
        ["request_id"],
        ["id"],
    )
    # ### end Alembic commands ###
