"""add_outoOfoOffice_to_users

Revision ID: 99ffc9a1c4cf
Revises: 626fe01567d4
Create Date: 2026-02-18 11:28:31.230695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ffc9a1c4cf'
down_revision: Union[str, Sequence[str], None] = '626fe01567d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_out_of_office', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_out_of_office')
    # ### end Alembic commands ###
