"""add approver_id to request_tracking

Revision ID: abaf58f17995
Revises: b37777b6b805
Create Date: 2026-02-23 16:19:27.296069

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abaf58f17995"
down_revision: Union[str, Sequence[str], None] = "b37777b6b805"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "request_tracking", sa.Column("approver_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "request_tracking", "users", ["approver_id"], ["id"])
    op.drop_index(
        op.f("ix_request_type_approvers_request_type_id"),
        table_name="request_type_approvers",
    )
    op.drop_index(
        op.f("ix_request_type_approvers_user_id"), table_name="request_type_approvers"
    )
    op.drop_constraint(
        op.f("request_type_approvers_user_id_fkey"),
        "request_type_approvers",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "request_type_approvers", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "request_type_approvers", type_="foreignkey")
    op.create_foreign_key(
        op.f("request_type_approvers_user_id_fkey"),
        "request_type_approvers",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_request_type_approvers_user_id"),
        "request_type_approvers",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_request_type_approvers_request_type_id"),
        "request_type_approvers",
        ["request_type_id"],
        unique=False,
    )
    op.drop_constraint(None, "request_tracking", type_="foreignkey")
    op.drop_column("request_tracking", "approver_id")
    # ### end Alembic commands ###
