"""eap-168 email verification

Revision ID: d185df90c12a
Revises: b37777b6b805
Create Date: 2026-03-08 22:11:33.077649

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d185df90c12a"
down_revision: Union[str, Sequence[str], None] = "b37777b6b805"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_request_type_approvers_request_type_id"),
        table_name="request_type_approvers",
    )
    op.drop_index(
        op.f("ix_request_type_approvers_user_id"), table_name="request_type_approvers"
    )
    op.drop_constraint(
        op.f("request_type_approvers_user_id_fkey"),
        "request_type_approvers",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "request_type_approvers", "users", ["user_id"], ["id"])
    op.add_column("users", sa.Column("is_email_verified", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_email_verified")
    op.drop_constraint(None, "request_type_approvers", type_="foreignkey")
    op.create_foreign_key(
        op.f("request_type_approvers_user_id_fkey"),
        "request_type_approvers",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_request_type_approvers_user_id"),
        "request_type_approvers",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_request_type_approvers_request_type_id"),
        "request_type_approvers",
        ["request_type_id"],
        unique=False,
    )
    # ### end Alembic commands ###
